@baseUrl=http://localhost:3000

### get todo
GET {{baseUrl}}/todo
Accept: application/json
Content-Type: application/json

### get todo by id
GET {{baseUrl}}/todo/2
Accept: application/json
Content-Type: application/json


### add todo
POST {{baseUrl}}/todo
Accept: application/json
Content-Type: application/json

{
    "name": "create todolist app",
    "description": "create containerized todolist app",
    "deadline": "2024-08-17"
}

### update todo
PUT {{baseUrl}}/todo/1
Accept: application/json
Content-Type: application/json

{
    "name": "create check todo app",
    "description": "create containerized check todo app",
    "deadline": "2024-08-17"
}

### check todo
PATCH {{baseUrl}}/todo/check/1
Accept: application/json
Content-Type: application/json

{
    "done": true
}