apiVersion: batch/v1
kind: Job
metadata:
  name: migration
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: fathur208/migration
          env:
          - name: DB_HOST
            value: "postgresql-service"
          - name: DB_PORT
            value: "5432"
          - name: DB_NAME
            value: "todolist"
          - name: DB_USER
            value: "admin"
          - name: DB_PASSWORD
            value: "password"
