apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /kubernetes/data/postgresql

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  labels:
    name: postgresql
spec:
  serviceName: postgresql-service
  replicas: 1
  selector:
    matchLabels:
      name: postgresql
  volumeClaimTemplates:
    - metadata:
        name: postgresql-volume-claim
      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi
  template:
    metadata:
      name: postgresql
      labels:
        name: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql-volume-claim
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_DB
              value: "todolist"
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "password"
